### 회원가입
POST http://localhost:8090/api/user/sign-up
Content-Type: application/json; charset=utf-8

{
  "userId" : "test",
  "userPw" : "test",
  "userNm" : "test",
  "email" : "test",
  "cellPhone" : "test"
}



