server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ssosung?serverTimezone=Asia/Seoul
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  decorator:
    datasource:
      p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing.include-parameter-values: true